### ISSUE TITLE
Adding new time tracking entry does not work

### ISSUE THREAD

**Issue by sherpa003** [VonRehbergConsulting/open-time-tracker#47]
Hello,
I tried to evaluate this app with my OpenProject 13.0.7 instance and it seems that basic functionality does not work.
If there is existing time entry, I can resume from it, add more time, save it and it works. 
But when I create new entry, track time and finish, the save does not work. It just tells me "something went wrong" in the app

On the server, it says:
openproject-web-1       | I, [2023-11-21T07:52:33.092255 #56]  INFO -- : Started POST "/api/v3/time_entries" for 31.47.97.70 at 2023-11-21 07:52:33 +0000
openproject-web-1       | I, [2023-11-21T07:52:33.110733 #56]  INFO -- : duration=17.43 db=3.10 view=14.33 status=422 method=POST path=/api/v3/time_entries params={"user"=>{"id"=>5}, "workPackage"=>{"href"=>"/api/v3/work_packages/37"}, "project"=>{"href"=>"/api/v3/projects/3"}, "spentOn"=>"2023-11-21", "hours"=>"PT05M", "comment"=>{"format"=>"plain", "raw"=>nil}} host=example.com user=5

For the working case, there is PATCH instead of POST, otherwise it looks similar

**Comment by shtangey** [comment]
Hello,
Can you please provide more information about the task? It's type etc.

**Comment by VonRehberg** [comment]
In case this is a docker/compose instance it would maybe also be good if you could share your compose file / environment variables.
If you are currently evaluating the app and don't use the OP instance productively, maybe you could also create a user for us? Prerequisite would be of course the instance is available from the internet.

**Comment by sherpa003** [comment]
> Hello, Can you please provide more information about the task? It's type etc.

I have single work package of "TASK" type assigned to the user, it is in progress.
there is single time tracking activity enabled "Other".

**Comment by sherpa003** [comment]
> In case this is a docker/compose instance it would maybe also be good if you could share your compose file / environment variables. If you are currently evaluating the app and don't use the OP instance productively, maybe you could also create a user for us? Prerequisite would be of course the instance is available from the internet.

It is fresh install based on this: https://github.com/opf/openproject-deploy
I only changed port, set https and have nginx proxy in front of it.

**Comment by VonRehberg** [comment]
Can you post your nginx config?
I suspect that there might be something misconfigured, because all requests except from the POST requests are working. Are you able to issue POST requests using postman?

**Comment by shtangey** [comment]
> > Hello, Can you please provide more information about the task? It's type etc.
> 
> I have single work package of "TASK" type assigned to the user, it is in progress. there is single time tracking activity enabled "Other".

Activity type is not specified in the request, and I believe it is set to management by default. Enabling management activity type should solve the issue.

**Comment by sherpa003** [comment]
> > > Hello, Can you please provide more information about the task? It's type etc.
> > 
> > 
> > I have single work package of "TASK" type assigned to the user, it is in progress. there is single time tracking activity enabled "Other".
> 
> Activity type is not specified in the request, and I believe it is set to management by default. Enabling management activity type should solve the issue.

You are right. This explains it. After enabling management activity, it works
