### ISSUE TITLE
Creating a WorkPackage through the app

### ISSUE THREAD

**Issue by oleksiiborysenko** [VonRehbergConsulting/open-time-tracker#48]
Hi again guys. We've had a discussion with @lindenthal and he asked me to extend the functionality of your app with several features. One of them should be a creating new WorkPackage from the app. It should be possible to select project, type of WorkPackage, title, description and date. I'm going to implement that. But before I start it is better to ask if you don't mind if I re-use your code for it. Also as a separate thing - @lindenthal mentioned that it would be good to cooperate with you by extending the functionality even more (of course it's a separate tasks with separate billings) also if you don't mind.

**Comment by VonRehberg** [comment]
Sure thing, sounds awesome! Let us know if you need anything from our side...
@shtangey fyi
