### ISSUE TITLE
Make assigned to me a filter option

### ISSUE THREAD

**Issue by ni-ka** [VonRehbergConsulting/open-time-tracker#62]
Hi,

Thanks for your app! We're currently evaluating open project, one functionality we currently use in Asana is time tracking by multiple people on the same task, for example for meetings. Currently the app only shows issues assigned to me. It would be great if the filter could be removed / made optional to allow to see all open tasks for the different projects.

I can try to find some time to do a pull request but currently not much extra time so creating this in case someone else would like to pick this up!

Cheers

**Comment by ni-ka** [comment]
Thanks @VonRehberg, interesting option, I didn't know about it and we can actually use that effectively for our needs. 

However, we often do track time to someone elses issue, for example if a task needs to be reviewed (for small tasks we don't necessarily create follow up tasks or assign for the review). As there is no way to change the assignee in the mobile app. a way to display all tasks or search would be great. 
There are other filters, so the current behavior could be a default but possible to uncheck if wanted by the user?

**Comment by shtangey** [comment]
Resolved in 1.6.0
